name: anhuiwatch
description: "Huami wearable watch faces"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  firebase_core: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
